name: Deploy to Edgeserver.io

on:
  push:
    branches:
      - "main"

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Edgeserver Upload
        uses: lvkdotsh/edgeserver-action@v0.0.34
        with:
          app_id: "80751380033179648"
          server: https://api.edgeserver.io
          token: ${{ secrets.EDGESERVER_TOKEN }}
          directory: dist
